- name: "Clone the {{ project_name }} from git"
  git:
      repo: "https://{{ git_root_url }}/{{ git_user_name }}/{{ project_name }}.git"
      dest: "{{ project_path }}"
      force: yes

- name: "Clone modules"
  git:
      repo: "https://{{ git_root_url }}/{{ git_user_name }}/modules.git"
      dest: "{{ project_path }}/modules"
      force: yes

- name: "Clone profiles"
  git:
      repo: "https://{{ git_root_url }}/{{ git_user_name }}/profiles.git"
      dest: "{{ project_path }}/profiles"
      force: yes


- name: "Make sure the {{ user_group }} is present"
  group:
    name: "{{ user_group }}"

- name: "Setup user for running {{ project_name }}"
  user:
      name: "{{ user_name }}"
      group: osinter
      groups: osinter,{{ user_group }}
      create_home: false
      home: "{{ project_path }}"
      shell: "{{ user_shell }}"
      password: "{{ user_password|password_hash('sha512') }}"

- name: "Changing the owner of the {{ project_path }} folder"
  file:
      dest: "{{ project_path }}"
      mode: 0740
      owner: "{{ user_name }}"
      group: "osinter"
      recurse: yes

- name: Write the URL for the Elasticsearch cluster to protected file
  copy:
    content: "{{ elastic_cluster_osinter_url }}"
    dest: "{{ project_path }}/.elasticsearch.url"
    owner: "{{ user_name }}"
    group: "{{ user_group }}"
    mode: 0400

- name: "Copy the Elasticsearch HTTPS cert to {{ project_path }}"
  copy:
    src: "{{ elastic_dir }}/config/certs/http_ca.crt"
    dest: "{{ project_path }}/.elasticsearch.crt"
    remote_src: yes
    mode: 0740
    owner: "{{ user_name }}"
    group: "osinter"
  when: elastic_dir is defined
