- name: Start setups
  hosts: all
  gather_facts: no
  become: yes
  pre_tasks:
    - name: "Saving the Elasticsearch cluster url"
      set_fact:
        elastic_cluster_url: "{{elastic_cluster_url}}"

    - name: Check if python3 is present
      raw: test -e /usr/bin/python3
      changed_when: false
      failed_when: false
      register: check_python

    - name: Try to install python3 if not present
      raw: "pacman -S --noconfirm python3; apt install -y python3; dnf -y install python3"
      when: check_python.rc != 0
      ignore_errors: yes

  tasks:

    - name: Gather fact now that python is installed
      setup:

    - name: Set path for distribution details
      set_fact:
        distDetailPath: "vars/distributionDetails/"

    - name: Import distro variables
      include_vars: "{{ item }}"
      when: "'{{ item }}' is file"
      loop:
        - '{{distDetailPath}}Default.json'
        - '{{distDetailPath}}{{ ansible_os_family }}.json'
        - '{{distDetailPath}}{{ ansible_distribution }}.json'
        - '{{distDetailPath}}{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.json'
        - '{{distDetailPath}}{{ ansible_distribution }}-{{ ansible_distribution_version }}.json'
      ignore_errors: yes

    - name: Import general purpose variables
      include_vars: "vars/general.json"

- hosts: all
  become: true
  roles:
    - prerequisites

- hosts: elasticsearch
  become: true
  roles:
    - elasticsearch

- hosts: backend
  become: true
  roles:
    - backend

- hosts: frontend
  become: true
  roles:
    - frontend
