# vim:ft=yaml.ansible:

- name: Start setups
  hosts: all
  gather_facts: false
  become: true

  pre_tasks:
    - name: Check if python3 is present
      ansible.builtin.raw: test -e /usr/bin/python3
      changed_when: false
      failed_when: false
      register: check_python

    - name: Try to install python3 if not present
      ansible.builtin.raw: "pacman -Sy --noconfirm python3; apt update; apt install -y python3; dnf -y install python3"
      when: check_python.rc != 0
      changed_when: check_python.rc != 0
      failed_when: false

  tasks:

    - name: Gather fact now that python is installed
      ansible.builtin.setup:

    - name: Set path for distribution details
      ansible.builtin.set_fact:
        dist_detail_path: "vars/distributionDetails/"

    - name: Import distro variables
      ansible.builtin.include_vars: "{{ item }}"
      when: "item is file"
      loop:
        - '{{ dist_detail_path }}Default.json'
        - '{{ dist_detail_path }}{{ ansible_os_family }}.json'
        - '{{ dist_detail_path }}{{ ansible_distribution }}.json'
        - '{{ dist_detail_path }}{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.json'
        - '{{ dist_detail_path }}{{ ansible_distribution }}-{{ ansible_distribution_version }}.json'

    - name: Import general purpose variables
      ansible.builtin.include_vars: "vars/general.json"

- name: Setup prerequisites
  hosts: all
  become: true
  roles:
    - prerequisites
