- name: Start setups
  hosts: all
  gather_facts: no
  become: yes
  tasks:

    - name: Gather fact now that python is installed
      setup:

    - name: Set path for distribution details
      set_fact:
        distDetailPath: "vars/distributionDetails/"

    - name: Import distro variables
      include_vars: "{{ item }}"
      when: "'{{ item }}' is file"
      loop:
        - '{{distDetailPath}}Default.json'
        - '{{distDetailPath}}{{ ansible_os_family }}.json'
        - '{{distDetailPath}}{{ ansible_distribution }}.json'
        - '{{distDetailPath}}{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.json'
        - '{{distDetailPath}}{{ ansible_distribution }}-{{ ansible_distribution_version }}.json'
      ignore_errors: yes

    - name: Import general purpose variables
      include_vars: "vars/general.json"

- hosts: all
  become: true
  roles:
    - prerequisites

- hosts: elasticsearch
  become: true
  roles:
    - elasticsearch

- hosts: backend
  become: true
  roles:
    - backend

- hosts: frontend
  become: true
  roles:
    - frontend
