- name: Update backend
  hosts: backend
  tasks:
    - name: Import general purpose variables
      include_vars: "vars/general.json"

    - name: Update backend
      include_role:
        name: update
      vars:
        project_name: "{{ dbserver_project_name }}"
        user_name: "{{ dbserver_user_name }}"

- name: Update frontend
  hosts: frontend
  become: yes
  tasks:
    - name: Import general purpose variables
      include_vars: "vars/general.json"

    - name: Import general purpose variables
      include_vars: "vars/general.json"

    - name: Update API
      include_role:
        name: update
      vars:
        project_name: "{{ dbserver_project_name }}"
        user_name: "{{ dbserver_user_name }}"

    - name: Update static frontend files
      include_role:
        name: setup_static_from_release
      vars:
        static_project_name: "webfrontend"
        project_path: "{{ root_path }}/{{ webserver_project_name }}"
        user_name: "{{ webserver_user_name }}"
        user_group: "{{ webserver_user_group }}"

    - name: Restart the webserver
      ansible.builtin.service:
        name: "OSINT{{ webserver_project_name }}.service"
        state: restarted
        enabled: yes
      become: yes
