- set_fact:
    project_name: "{{ dbserver_project_name }}"
    project_path: "{{ root_path }}/{{ dbserver_project_name }}"
    user_name: "{{ dbserver_user_name }}"
    user_group: "{{ dbserver_user_group }}"
    user_shell: "{{ dbserver_user_shell }}"
    user_password: "{{ dbserver_user_password }}"

- name: Setup files and users for the backend
  include_role:
    name: setup_file_and_user

- name: Setup the python enviroment for the backend
  include_role:
    name: setup_python_venv
    apply:
      become: yes
      become_user: "{{ user_name }}"

- name: Install firefox for doing the scraping
  package:
    name: "{{ firefox_package }}"
    state: latest

- name: Initialize elasticsearch index and local enviroment using python script from OSINTbackend
  shell: 'cd /srv/{{ project_name }};ELASTICSEARCH_URL={{ elastic_cluster_url }} {{ project_name }}env/bin/python3 -m "scripts.initiateScrapingBackend"'
  become: yes
  become_user: "{{ user_name }}"

- name: Setup cronjob for automatically scraping articles
  include_tasks: "cron.yml"
