- set_fact:
    project_name: "{{ webserver_project_name }}"
    project_path: "{{ root_path }}/{{ webserver_project_name }}"
    user_name: "{{ webserver_user_name }}"
    user_password: "{{ webserver_user_password }}"
    user_group: "{{ webserver_user_group }}"
    user_shell: "{{ webserver_user_shell }}"

- name: Setup files and users for the webserver
  include_role:
    name: setup_file_and_user

- name: Clone frontend files too
  git:
    repo: "https://{{ git_root_url }}/{{ git_user_name }}/webfrontend.git"
    dest: "{{ project_path }}/webfrontend"
    force: yes
  become: yes
  become_user: "{{ user_name }}"

- name: Clone files for blog too
  git:
    repo: "https://{{ git_root_url }}/{{ git_user_name }}/blog.git"
    dest: "{{ project_path }}/blog"
    force: yes
  become: yes
  become_user: "{{ user_name }}"

- name: Setup the python enviroment for the webserver
  include_role:
    name: setup_python_venv
    apply:
      become: yes
      become_user: "{{ user_name }}"

- name: Setup the needed files for TLS
  include_tasks: "certificates.yml"
  args:
    apply:
      become: yes
      become_user: "{{ user_name }}"

- name: Setup the service for the gunicorn instance
  include_tasks: "gunicorn.yml"

- name: Check for SELinux and apply the right context if present
  include_tasks: "selinux.yml"

- name: Finally, setting up the nginx service
  include_tasks: "nginx.yml"
