- set_fact:
    project_name: "{{ webserver_project_name }}"
    project_path: "{{ root_path }}/{{ webserver_project_name }}"
    user_name: "{{ webserver_user_name }}"
    user_password: "{{ webserver_user_password }}"
    user_group: "{{ webserver_user_group }}"
    user_shell: "{{ webserver_user_shell }}"

- name: Setup files and users for the webserver
  include_tasks: "{{ playbook_dir }}/generic/setupFileAndUser.yml"

- name: Setup the python enviroment for the webserver
  include_tasks: "{{ playbook_dir }}/generic/pythonEnviroment.yml"

- name: Setup the needed files for TLS
  include_tasks: "{{ playbook_dir }}/webserver/certificates.yml"
  args:
    apply:
      become: yes
      become_user: "{{ user_name }}"
      become_method: "sudo"

- name: Setup the service for the gunicorn instance
  include_tasks: "{{ playbook_dir }}/webserver/gunicorn.yml"
  args:
    apply:
      become: yes
      become_user: "{{ user_name }}"
      become_method: "sudo"

- name: Check for SELinux and apply the right context if present
  include_tasks: "{{ playbook_dir }}/webserver/selinux.yml"

- name: Finally, setting up the nginx service
  include_tasks: "{{ playbook_dir }}/webserver/nginx.yml"
