- name: Updating the system
  package:
    update_cache: yes
    upgrade: yes

- name: Installing python dependencies
  package:
    name: "{{ item }}"
    state: latest
  with_items: "{{ python_dependencies }}"

- name: Install dependencies for installing the python cryptography library where needed
  package:
    name: "{{ item }}"
    state: latest
  with_items: "{{cryptography_dependencies}}"
  when: cryptography_dependencies is defined

- name: Install python cryptography library for generating TLS certificates.
  pip:
    name: "{{ item }}"
  with_items:
    - wheel
    - setuptools-rust
    - cryptography

- name: Install git
  package:
    name: git
    state: latest

- name: Install ACL used when becomming less priviledged user
  package:
    name: acl
    state: latest

- name: Genereate the needed locales
  ansible.builtin.shell: "grep '^en_US\\.UTF-8 UTF-8$' /etc/locale.gen || echo 'en_US.UTF-8 UTF-8' >> /etc/locale.gen; locale-gen"
