- name: Updating the system
  package:
    update_cache: yes
    upgrade: yes
  when: ansible_os_family != "RedHat"

- name: Upgrade RHEL Family OS packages
  yum:
    name: '*'
    state: latest
  when: ansible_os_family == "RedHat"

- name: Installing python dependencies
  package:
    name: "{{ item }}"
    state: latest
  with_items: "{{ python_dependencies }}"

- name: Install dependencies for installing the python cryptography library where needed
  package:
    name: "{{ item }}"
    state: latest
  with_items: "{{cryptography_dependencies}}"
  when: cryptography_dependencies is defined

- name: Install python cryptography library for generating TLS certificates.
  pip:
    name: "{{ item }}"
  with_items:
    - wheel
    - setuptools-rust
    - cryptography
  when: cryptography_library is not defined

- name: Install python cryptography library using offical repos
  package:
    name: "{{ item }}"
    state: latest
  with_items: "{{cryptography_library}}"
  when: cryptography_library is defined

- name: Install git
  package:
    name: git
    state: latest

- name: Install ACL used when becomming less priviledged user
  package:
    name: acl
    state: latest

- name: Install locale files for generating locales
  package:
    name: "{{ item }}"
    state: latest
  with_items: "{{locale_dependencies}}"
  when: locale_dependencies is defined

- name: Genereate the needed locales
  ansible.builtin.shell: "localedef -v -c -i en_US -f UTF-8 en_US.UTF-8"
  register: localedef_response
  failed_when: localedef_response.rc != 0 and localedef_response.rc != 1
