---


- name: Make sure python is installed
  import_playbook: "{{ playbook_dir }}/python.yml"

- name: Installing prerequisite
  hosts: all
  become: true
  tasks:

    - name: Setting the distribution-specific variables for Archlinux
      set_fact: 
        pip_package: "python-pip"
      when: ansible_distribution == "Archlinux"

    - name: Setting the distribution-specific variables for Debian/Ubuntu
      set_fact:
        pip_package: "python3-pip"
      when: ansible_distribution in ["Debian", "Ubuntu"]

    - name: Updating the system
      package:
        update_cache: yes
        upgrade: yes

    - name: Install pip
      package:
        name: "{{ pip_package }}"
        state: latest

    - name: Install git
      package:
        name: git
        state: latest

    - name: Genereate the needed locales
      ansible.builtin.shell: "grep '^en_US\\.UTF-8 UTF-8$' /etc/locale.gen || echo 'en_US.UTF-8 UTF-8' >> /etc/locale.gen; locale-gen"
