- name: Check if python is present
  raw: test -e /usr/bin/python
  changed_when: false
  failed_when: false
  register: check_python

- name: Try to install python if not present
  raw: "pacman -S --noconfirm python3; apt install -y python3"
  when: check_python.rc != 0
  ignore_errors: yes
