- name: Download static files
  ansible.builtin.get_url:
    url: "https://{{ git_root_url }}/{{ git_user_name }}/{{ static_project_name }}/-/releases/permalink/latest/downloads/build/build.tar.gz"
    dest: "/tmp/build.tar.gz"
    force: yes

- name: Create folder for hosting static files
  ansible.builtin.file:
    path: "{{ project_path }}/{{ static_project_name }}"
    state: directory
    mode: '0555'
    owner: "{{ user_name }}"
    group: "{{ user_group }}"

- name: Extracting static files
  ansible.builtin.unarchive:
    src: "/tmp/build.tar.gz"
    dest: "{{ project_path }}/{{ static_project_name }}"
    remote_src: yes
    mode: '0555'
    owner: "{{ user_name }}"
    group: "{{ user_group }}"

