- name: "Setting new root path for Elasticsearch"
  set_fact:
    elastic_dir: "{{ elastic_dir.split('/')[:-1]|join('/')}}"

- name: "Get the list of services"
  service_facts:

- name: "Stop the Elasticsearch service"
  systemd:
    name: "elasticsearch.service"
    state: "stopped"
  when: "'elasticsearch.service' in services"

- name: "Make sure the {{ elastic_user_group }} group is present"
  group:
      name: "{{ elastic_user_group }}"

- name: "Setup user for running Elasticsearch"
  user:
      name: "{{ elastic_user_name }}"
      group: "{{ elastic_user_group }}"
      create_home: false
      home: "{{ elastic_dir }}"
      shell: "{{ elastic_user_shell }}"
      password: "{{ elastic_user_password|password_hash('sha512') }}"

- name: "Create folder for holding the Elasticsearch files"
  file:
    path: "{{ elastic_dir }}"
    state: directory
    mode: 0740
    owner: "{{ elastic_user_name }}"
    group: "{{ elastic_user_group }}"

- name: "Download and extract Elasticsearch files"
  unarchive:
    src: "{{ elastic_install_url }}"
    dest: "{{ elastic_dir }}"
    remote_src: yes
    keep_newer: yes
    mode: 0740
    owner: "{{ elastic_user_name }}"
    group: "{{ elastic_user_group }}"
    list_files: yes
  register: elastic_archive_contents

- name: "Setting new path to unarchived Elasticsearch"
  set_fact:
    elastic_dir: "{{ elastic_archive_contents.dest }}/{{ elastic_archive_contents.files[0] }}"

- name: "Create data and log directory for Elasticsearch"
  file:
    path: "{{ elastic_dir }}/{{ item }}"
    state: directory
    mode: 0740
    owner: "{{ elastic_user_name }}"
    group: "{{ elastic_user_group }}"
  with_items: ["data", "logs"]

- name: "Change vm.max_map_count"
  shell: "echo 'vm.max_map_count = 262144' >> /etc/sysctl.conf && sysctl -p"

- name: "Create Elasticsearch keystore"
  command:
    cmd: "{{ elastic_dir }}/bin/elasticsearch-keystore create"
    stdin: "n"
  become: yes
  become_user: "{{ elastic_user_name }}"

- name: "Remove existing bootstrap password"
  command:
    cmd: "{{ elastic_dir }}/bin/elasticsearch-keystore remove 'bootstrap.password'"
  become: yes
  become_user: "{{ elastic_user_name }}"
  ignore_errors: yes

- name: "Set password for elastic user in Elasticsearch"
  command:
    cmd: "{{ elastic_dir }}/bin/elasticsearch-keystore add 'bootstrap.password'"
    stdin: "{{ elastic_elastic_password }}"
  become: yes
  become_user: "{{ elastic_user_name }}"

- name: "Install service for running the Elasticsearch"
  template:
    src: "elasticsearch.service"
    dest: "/etc/systemd/system/"

- name: Check if SELinux is present and enabled
  command: /usr/sbin/selinuxenabled
  ignore_errors: yes
  register: selinux_status

- name: "Apply new SELinux context for custom Elasticsearch bin directory to make it executable"
  command: chcon -Rv --type=bin_t "{{ elastic_dir }}/bin"
  when: selinux_status.rc == 0

- name: "Restart Elasticsearch service, also issue daemon-reload to pick up config changes"
  systemd:
    state: "restarted"
    enabled: yes
    daemon_reload: yes
    name: "elasticsearch.service"

- name: "Wait for Elasticsearch to come online again"
  wait_for:
    port: 9200

- name: "Wait to make sure Elasticsearch is properly initialized"
  pause:
    minutes: 1
