- name: "Clone the {{ project_name }} from git"
  git:
      repo: "https://{{ git_root_url }}/{{ git_user_name }}/{{ project_name }}.git"
      dest: "{{ project_path }}"
      force: yes

- name: "Clone OSINTmodules"
  git:
      repo: "https://{{ git_root_url }}/{{ git_user_name }}/OSINTmodules.git"
      dest: "{{ project_path }}/OSINTmodules"
      force: yes

- name: "Clone OSINTprofiles"
  git:
      repo: "https://{{ git_root_url }}/{{ git_user_name }}/OSINTprofiles.git"
      dest: "{{ project_path }}/OSINTprofiles"
      force: yes

- name: "Make sure the osinter group is present"
  group:
      name: "osinter"

- name: "Make sure the {{ user_group }} is present"
  group:
    name: "{{ user_group }}"

- name: "Setup user for running {{ project_name }}"
  user:
      name: "{{ user_name }}"
      groups: osinter,{{ user_group }}
      create_home: false
      home: "{{ project_path }}"
      shell: "{{ user_shell }}"
      password: "{{ user_password|password_hash('sha512') }}"

- name: "Changing the owner of the {{ project_path }} folder"
  file:
      dest: "{{ project_path }}"
      mode: 0744
      owner: "{{ user_name }}"
      group: "{{ user_group }}"
      recurse: yes
- name: "Changing the permissions of the {{ project_path }} folder to 755 so the articles is world readable"
  file:
    dest: "{{ project_path }}"
    mode: 0755
