- name: Install cron package for handling the crontab
  package:
    name: "{{ cron_package }}"
    state: latest

- name: Start the newly installed cron daemon and enable it
  ansible.builtin.service:
    name: "{{ cron_package }}"
    state: started
    enabled: yes


- name: Setup crontab for scraping
  ansible.builtin.cron:
    name: OSINTbackend scraping
    special_time: hourly
    job: 'cd /srv/{{ project_name }} && {{ project_name }}env/bin/python3 -m scripts.scrapeAndStore >> ./logs/scrape.log 2>> ./logs/scrapeErrors.log'
  become: yes
  become_user: "{{ user_name }}"
  become_method: "sudo"
