- set_fact:
    project_name: "OSINTbackend"
    project_path: "/srv/OSINTbackend"
    user_name: "{{ dbserver_user_name }}"
    user_group: "{{ dbserver_user_group }}"
    user_shell: "{{ dbserver_user_shell }}"
    user_password: "{{ dbserver_user_password }}"

- include_tasks: "{{ playbook_dir }}/generic/setupFileAndUser.yml"

- name: Setup the python enviroment for
  include_tasks: "{{ playbook_dir }}/generic/pythonEnviroment.yml"
  args:
    apply:
      become: yes
      become_user: "{{ user_name }}"
      become_method: "sudo"

- name: Install firefox for doing the scraping
  package:
    name: "{{ firefox_package }}"
    state: latest

- include_tasks: "{{ playbook_dir }}/dbserver/postgresql.yml"

- name: Setup own postgresql DB and apply custom configurations
  include_tasks: "{{ playbook_dir }}/dbserver/initDB.yml"
  args:
    apply:
      become: yes
      become_user: "{{ user_name }}"
      become_method: "sudo"


- name: Setup crontab for performing the scraping hourly
  include_tasks: "{{ playbook_dir }}/dbserver/cron.yml"

- name: Perform scraping for the first time
  shell: "cd /srv/OSINTbackend && ./OSINTbackendenv/bin/python3 -m 'scripts.scrapeAndStore'"
  become: yes
  become_method: "sudo"
  become_user: "{{ user_name }}"
