- hosts: all

- name: Setup files and users for the dbserver
  import_playbook: "{{ playbook_dir }}/../generic/setupFileAndUser.yml"
  vars:
    user_group: "osinter-db"
    user_name: "osinter-db"
    project_name: "OSINTbackend"
    user_password: ""

- name: Setup the python enviroment for the dbserver
  import_playbook: "{{ playbook_dir }}/../generic/pythonEnviroment.yml"
  vars:
    project_name: "OSINTbackend"
    user_name: "osinter-db"

- name: Install firefox for doing the scraping
  hosts: all
  become: yes
  tasks:
    - package:
        name: firefox
        state: latest

- name: Setup postgresql
  import_playbook: "{{ playbook_dir }}/postgresql.yml"

- name: Setup own postgresql DB and apply custom configurations
  import_playbook: "{{ playbook_dir}}/initDB.yml"
  vars:
    user_name: "osinter-db"
    project_name: "OSINTbackend"

- name: Setup crontab for performing the scraping hourly
  import_playbook: "{{ playbook_dir }}/cron.yml"
  vars:
    user_name: "osinter-db"
    project_name: "OSINTbackend"
