- hosts: all

- name: Setup files and users for the dbserver
  import_playbook: "{{ playbook_dir }}/../generic/setupFileAndUser.yml"
  vars:
    user_group: "osinter-db"
    user_name: "osinter-db"
    project_name: "OSINTbackend"
    user_password: ""

- name: Setup the python enviroment for the dbserver
  import_playbook: "{{ playbook_dir }}/../generic/pythonEnviroment.yml"
  vars:
    project_name: "OSINTbackend"
    user_name: "osinter-db"

- name: Install firefox for doing the scraping
  import_playbook: "{{ playbook_dir }}/firefox.yml"

- name: Setup postgresql
  import_playbook: "{{ playbook_dir }}/postgresql.yml"

- name: Setup own postgresql DB and apply custom configurations
  import_playbook: "{{ playbook_dir}}/initDB.yml"
  vars:
    user_name: "osinter-db"
    project_name: "OSINTbackend"

- name: Setup crontab for performing the scraping hourly
  import_playbook: "{{ playbook_dir }}/cron.yml"
  vars:
    user_name: "osinter-db"
    project_name: "OSINTbackend"

- name: Perfom scraping first time
  hosts: all
  tasks:
    - name: Perform scraping
      shell: "cd /srv/OSINTbackend && ./OSINTbackendenv/bin/python3 -m 'scripts.scrapeAndStore'"
  become: yes
  become_method: "sudo"
  become_user: "osinter-db"
