- name: Install cron package for handling the crontab
  package:
    name: "{{ cron_package }}"
    state: latest

- name: Start the newly installed cron daemon and enable it
  ansible.builtin.service:
    name: "{{ cron_daemon if cron_daemon is defined else cron_package }}"
    state: started
    enabled: yes


- name: Setup crontab for scraping
  ansible.builtin.cron:
    name: OSINTbackend scraping
    special_time: hourly
    job: 'cd {{ root_path }}/{{ dbserver_project_name }} && {{ dbserver_project_name }}env/bin/python3 -m scripts.scrapeAndStore >> ./logs/scrape.log 2>> ./logs/scrapeErrors.log && pg_dump -U reader osinter > ./articles/database.sql'
  become: yes
  become_user: "{{ dbserver_user_name }}"
  become_method: "sudo"

- name: "Setup crontab for updating {{ dbserver_project_name }}"
  ansible.builtin.cron:
    name: OSINTbackend scraping
    special_time: hourly
    job: 'cd {{ root_path }}/{{ dbserver_project_name }} && git pull origin master'
  become: yes
  become_user: "{{ dbserver_user_name }}"
  become_method: "sudo"

- name: "Setup crontab for updating {{ webserver_project_name }}"
  ansible.builtin.cron:
    name: OSINTbackend scraping
    special_time: hourly
    job: 'cd {{ root_path }}/{{ webserver_project_name }} && git pull origin master'
  become: yes
  become_user: "{{ webserver_user_name }}"
  become_method: "sudo"
