- name: Start setups
  hosts: all
  gather_facts: no
  become: yes
  tasks:
    - name: Make sure python is installed
      include_tasks: "{{ playbook_dir }}/prerequisites/python.yml"

    - name: Gather fact now that python is installed
      setup:

    - name: Set path for distribution details
      set_fact:
        distDetailPath: "{{ playbook_dir }}/../vars/distributionDetails/"

    - name: Import distro variables
      include_vars: "{{ item }}"
      when: "'{{ item }}' is file"
      loop:
        - '{{distDetailPath}}Default.json'
        - '{{distDetailPath}}{{ ansible_os_family }}.json'
        - '{{distDetailPath}}{{ ansible_distribution }}.json'
        - '{{distDetailPath}}{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.json'
        - '{{distDetailPath}}{{ ansible_distribution }}-{{ ansible_distribution_version }}.json'
      ignore_errors: yes

    - name: Import general purpose variables
      include_vars: "{{ playbook_dir }}/../vars/general.json"

    - name: Setup the prerequisites
      include_tasks: "{{ playbook_dir }}/prerequisites/main.yml"

    - name: Setup the webserver
      include_tasks: "{{ playbook_dir }}/webserver/main.yml"

    - name: Setup the database server
      include_tasks: "{{ playbook_dir }}/dbserver/main.yml"

    - name: Setup the needed crontabs
      include_tasks: "{{ playbook_dir }}/cron.yml"

    - name: Perform scraping for the first time
      shell: "cd /srv/OSINTbackend && ./OSINTbackendenv/bin/python3 -m 'scripts.scrapeAndStore'"
      become: yes
      become_method: "sudo"
      become_user: "{{ user_name }}"
