- name: Start setups
  hosts: all
  gather_facts: no
  become: yes
  tasks:
    - name: Make sure python is installed
      include_tasks: "{{ playbook_dir }}/prerequisites/python.yml"

    - name: Gather fact now that python is installed
      setup:

    - name: Import distro variables
      include_vars: "{{ lookup('first_found', params) }}"
      vars:
        params:
          files:
            - '{{ ansible_distribution }}-{{ ansible_distribution_version }}.json'
            - '{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.json'
            - '{{ ansible_distribution }}.json'
            - '{{ ansible_os_family }}.json'
            - 'Default.json'
          paths:
            - '{{ playbook_dir }}/../vars/distributionDetails'

    - name: Import general purpose variables
      include_vars: "{{ playbook_dir }}/../vars/general.json"

    - name: Setup the prerequisites
      include_tasks: "{{ playbook_dir }}/prerequisites/main.yml"

    - name: Setup the webserver
      include_tasks: "{{ playbook_dir }}/webserver/main.yml"

    - name: Setup the database server
      include_tasks: "{{ playbook_dir }}/dbserver/main.yml"
